name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v6.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: dokku.kevinbongart.net
        PROJECT: cards
        BRANCH: main
